### ISSUE TITLE
DSM_Auth 변경사항 반영

### ISSUE THREAD

**Issue by jeongjiwoo0522** [semicolonDSM/DDYZD_V2_FrontEnd#106]
https://github.com/semicolonDSM/DDYZD_FrontEnd/blob/dfb1baaa446e643d631d8f2a67677cae9165bf93/src/components/Main/Main.tsx#L15

*  token.getToken(res.data['access-token']) 이 부분에서 필드가 access_token으로 변경되었습니다

**Comment by eungyeole** [comment]
해결
